apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: elastic
  namespace: elastic-system
spec:
  version: 8.19.2
  count: 1
  elasticsearchRef:
    name: elastic
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          requests:
            cpu: 0
            memory: 0
          limits:
            cpu: 1
            memory: "1Gi"
